name: Gerar Ideias para TikTok

on:
  schedule:
    - cron: '0 11 * * *'  # Roda diariamente às 08h (BRT)
  workflow_dispatch:

jobs:
  gerar-ideias:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install openai

      - name: Rodar o script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python tikedutor.py

      - name: Upload do arquivo de ideias
        uses: actions/upload-artifact@v4
        with:
          name: ideias-tiktok
          path: ideias_tiktok_*.txt